export const datos = [
    {
        id:0,
        nombre:"rinel",
        imagen:"https://randomuser.me/api/portraits/men/64.jpg",
        edad:25,
    },
    {
        id:1,
        nombre:"rinel",
        imagen:"https://randomuser.me/api/portraits/women/3.jpg",
        edad:25, 
    },
    {
        id:2,
        nombre:"rinel",
        imagen:"https://randomuser.me/api/portraits/men/39.jpg",
        edad:25, 
    },
    {
        id:3,
        nombre:"rinel",
        imagen:"https://randomuser.me/api/portraits/women/68.jpg",
        edad:25, 
    },
    {
        id:4,
        nombre:"rinel",
        imagen:"https://randomuser.me/api/portraits/women/91.jpg",
        edad:25, 
    },
    {
        id:5,
        nombre:"rinel",
        imagen:"https://randomuser.me/api/portraits/men/53.jpg",
        edad:25, 
    },
]