export const useStyles = (theme) =>({
    head:{
        display:"flex",
        flexDirection:"row",
        alignItems:"center",
        justifyContent:"center",
    },
    box2:{
        display:"flex",
        justifyContent:"center",
        alignItems:"center",
        flexDirection:"row",
    },
    barra:{
        border:"3px #89061C solid",
        display:"flex",
        backgroundColor:"#DC0A2D",
        flexDirection:"column",
        justifyContent:"space-between",
        alignItems:"stretch",
    },
    clip:{
        border:"2px #000 solid",
        borderRadius:"5px",
    },
    clipwhite:{
        backgroundColor:"#E9667C",
        border:"none",
        marginLeft:"4px",
    },
    main:{
        backgroundColor:"#DC0A2D",
        borderBottom:"9px #89061C solid",
        flexDirection:"row",
        padding:"5px",
    },
    crblue:{
        borderRadius:"90%",
        backgroundColor:"#28AAFD",
        border:"3px white solid",
    },
    crred:{
        borderRadius:"90%",
        backgroundColor:"#A20620",
        border:"1px #000 solid",
        marginRight:"5px",
        marginLeft:"10px",
    },
    cryellow:{
        borderRadius:"90%",
        backgroundColor:"#A4900F",
        border:"1px #000 solid",
        marginRight:"5px", 
    },
    crgreen:{
        borderRadius:"90%",
        backgroundColor:"#5BAA67",
        border:"1px #000 solid",     
    },
    display:{
        alignItems:"center",
        justifyContent:"center",
        backgroundColor:"#DC0A2D",
    },
    screen:{
        backgroundColor:"#DEDEDE",
    },
    dots:{
        marginTop:"5px",
        justifyContent:"center",
    },
    puntos:{
        backgroundColor:"#89061C",
        marginRight:"10px",
        borderRadius:"90%",
    },
    pokemoncont:{
        display:"flex",
        alignItems:"center",
        justifyContent:"center",
        backgroundColor:"#DC0A2D",
    },
    pokemonlist:{
        display:"flex",
        flexDirection:"column",
        flexWrap:"wrap",
        padding:"10px",
        backgroundColor:"#232323",
    },
    cuadros:{
        display:"flex",
        alignItems:"center",
        justifyContent:"center",
        flexDirection:"row",
        backgroundColor:"#DC0A2D",
    },
    cuadritos:{
        border:"1px #000 solid",
        backgroundColor:"#28AAFD",
    },
    botones:{
        backgroundColor:"#DC0A2D",
    },
    box4:{
        marginTop:"5px",
        backgroundColor:"#232323",
        justifyContent:"center",
        alignItems:"center",
    },
    root:{
        display:"flex",
        flexDirection:"row",
    },
    action:{
        width:"40%",
        height:"100px",
        display:"flex",
        justifyContent:"center",
        alignItems:"center",
        backgroundColor:"#355A95",
    },
    descripciones:{
        width:"60%",
        height:"100px",
        display:"flex",
        flexDirection:"column",
        padding:"5px",
    },
    large: {
        width: theme.spacing(10),
        height: theme.spacing(10),
        backgroundColor:"#FFCB04",
    },
    size:{
        fontSize:"12px",
    },
})